// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	database "github.com/capyrpi/api/internal/database"
	mock "github.com/stretchr/testify/mock"

	pgtype "github.com/jackc/pgx/v5/pgtype"

	uuid "github.com/google/uuid"
)

// Querier is an autogenerated mock type for the Querier type
type Querier struct {
	mock.Mock
}

// AddEventHost provides a mock function with given fields: ctx, arg
func (_m *Querier) AddEventHost(ctx context.Context, arg database.AddEventHostParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for AddEventHost")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.AddEventHostParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddOrgMember provides a mock function with given fields: ctx, arg
func (_m *Querier) AddOrgMember(ctx context.Context, arg database.AddOrgMemberParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for AddOrgMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.AddOrgMemberParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateBotToken provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateBotToken(ctx context.Context, arg database.CreateBotTokenParams) (database.BotToken, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateBotToken")
	}

	var r0 database.BotToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.CreateBotTokenParams) (database.BotToken, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.CreateBotTokenParams) database.BotToken); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(database.BotToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.CreateBotTokenParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateEvent provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateEvent(ctx context.Context, arg database.CreateEventParams) (database.Event, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateEvent")
	}

	var r0 database.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.CreateEventParams) (database.Event, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.CreateEventParams) database.Event); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(database.Event)
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.CreateEventParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateLink provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateLink(ctx context.Context, arg database.CreateLinkParams) (database.Link, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateLink")
	}

	var r0 database.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.CreateLinkParams) (database.Link, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.CreateLinkParams) database.Link); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(database.Link)
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.CreateLinkParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateOrganization provides a mock function with given fields: ctx, name
func (_m *Querier) CreateOrganization(ctx context.Context, name string) (database.Organization, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrganization")
	}

	var r0 database.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (database.Organization, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) database.Organization); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(database.Organization)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUser provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateUser(ctx context.Context, arg database.CreateUserParams) (database.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 database.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.CreateUserParams) (database.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.CreateUserParams) database.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(database.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.CreateUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteEvent provides a mock function with given fields: ctx, eid
func (_m *Querier) DeleteEvent(ctx context.Context, eid uuid.UUID) error {
	ret := _m.Called(ctx, eid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, eid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteLink provides a mock function with given fields: ctx, lid
func (_m *Querier) DeleteLink(ctx context.Context, lid uuid.UUID) error {
	ret := _m.Called(ctx, lid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, lid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteOrganization provides a mock function with given fields: ctx, oid
func (_m *Querier) DeleteOrganization(ctx context.Context, oid uuid.UUID) error {
	ret := _m.Called(ctx, oid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrganization")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, oid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUser provides a mock function with given fields: ctx, uid
func (_m *Querier) DeleteUser(ctx context.Context, uid uuid.UUID) error {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, uid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBotTokenByHash provides a mock function with given fields: ctx, tokenHash
func (_m *Querier) GetBotTokenByHash(ctx context.Context, tokenHash string) (database.BotToken, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetBotTokenByHash")
	}

	var r0 database.BotToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (database.BotToken, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) database.BotToken); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Get(0).(database.BotToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEventByID provides a mock function with given fields: ctx, eid
func (_m *Querier) GetEventByID(ctx context.Context, eid uuid.UUID) (database.Event, error) {
	ret := _m.Called(ctx, eid)

	if len(ret) == 0 {
		panic("no return value specified for GetEventByID")
	}

	var r0 database.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (database.Event, error)); ok {
		return rf(ctx, eid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) database.Event); ok {
		r0 = rf(ctx, eid)
	} else {
		r0 = ret.Get(0).(database.Event)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, eid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEventRegistrations provides a mock function with given fields: ctx, eid
func (_m *Querier) GetEventRegistrations(ctx context.Context, eid uuid.UUID) ([]database.GetEventRegistrationsRow, error) {
	ret := _m.Called(ctx, eid)

	if len(ret) == 0 {
		panic("no return value specified for GetEventRegistrations")
	}

	var r0 []database.GetEventRegistrationsRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]database.GetEventRegistrationsRow, error)); ok {
		return rf(ctx, eid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []database.GetEventRegistrationsRow); ok {
		r0 = rf(ctx, eid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.GetEventRegistrationsRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, eid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLinkByEndpointURL provides a mock function with given fields: ctx, endpointUrl
func (_m *Querier) GetLinkByEndpointURL(ctx context.Context, endpointUrl string) (database.Link, error) {
	ret := _m.Called(ctx, endpointUrl)

	if len(ret) == 0 {
		panic("no return value specified for GetLinkByEndpointURL")
	}

	var r0 database.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (database.Link, error)); ok {
		return rf(ctx, endpointUrl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) database.Link); ok {
		r0 = rf(ctx, endpointUrl)
	} else {
		r0 = ret.Get(0).(database.Link)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, endpointUrl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLinkByLID provides a mock function with given fields: ctx, lid
func (_m *Querier) GetLinkByLID(ctx context.Context, lid uuid.UUID) (database.Link, error) {
	ret := _m.Called(ctx, lid)

	if len(ret) == 0 {
		panic("no return value specified for GetLinkByLID")
	}

	var r0 database.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (database.Link, error)); ok {
		return rf(ctx, lid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) database.Link); ok {
		r0 = rf(ctx, lid)
	} else {
		r0 = ret.Get(0).(database.Link)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, lid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrgMembers provides a mock function with given fields: ctx, oid
func (_m *Querier) GetOrgMembers(ctx context.Context, oid uuid.UUID) ([]database.GetOrgMembersRow, error) {
	ret := _m.Called(ctx, oid)

	if len(ret) == 0 {
		panic("no return value specified for GetOrgMembers")
	}

	var r0 []database.GetOrgMembersRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]database.GetOrgMembersRow, error)); ok {
		return rf(ctx, oid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []database.GetOrgMembersRow); ok {
		r0 = rf(ctx, oid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.GetOrgMembersRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, oid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrganizationByID provides a mock function with given fields: ctx, oid
func (_m *Querier) GetOrganizationByID(ctx context.Context, oid uuid.UUID) (database.Organization, error) {
	ret := _m.Called(ctx, oid)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationByID")
	}

	var r0 database.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (database.Organization, error)); ok {
		return rf(ctx, oid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) database.Organization); ok {
		r0 = rf(ctx, oid)
	} else {
		r0 = ret.Get(0).(database.Organization)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, oid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotalVisits provides a mock function with given fields: ctx, lid
func (_m *Querier) GetTotalVisits(ctx context.Context, lid uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, lid)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalVisits")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return rf(ctx, lid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = rf(ctx, lid)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, lid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByEmail provides a mock function with given fields: ctx, personalEmail
func (_m *Querier) GetUserByEmail(ctx context.Context, personalEmail pgtype.Text) (database.User, error) {
	ret := _m.Called(ctx, personalEmail)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 database.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.Text) (database.User, error)); ok {
		return rf(ctx, personalEmail)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.Text) database.User); ok {
		r0 = rf(ctx, personalEmail)
	} else {
		r0 = ret.Get(0).(database.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.Text) error); ok {
		r1 = rf(ctx, personalEmail)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: ctx, uid
func (_m *Querier) GetUserByID(ctx context.Context, uid uuid.UUID) (database.User, error) {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 database.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (database.User, error)); ok {
		return rf(ctx, uid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) database.User); ok {
		r0 = rf(ctx, uid)
	} else {
		r0 = ret.Get(0).(database.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserEvents provides a mock function with given fields: ctx, uid
func (_m *Querier) GetUserEvents(ctx context.Context, uid uuid.UUID) ([]database.GetUserEventsRow, error) {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for GetUserEvents")
	}

	var r0 []database.GetUserEventsRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]database.GetUserEventsRow, error)); ok {
		return rf(ctx, uid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []database.GetUserEventsRow); ok {
		r0 = rf(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.GetUserEventsRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserOrganizations provides a mock function with given fields: ctx, uid
func (_m *Querier) GetUserOrganizations(ctx context.Context, uid uuid.UUID) ([]database.GetUserOrganizationsRow, error) {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for GetUserOrganizations")
	}

	var r0 []database.GetUserOrganizationsRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]database.GetUserOrganizationsRow, error)); ok {
		return rf(ctx, uid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []database.GetUserOrganizationsRow); ok {
		r0 = rf(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.GetUserOrganizationsRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsEventAdmin provides a mock function with given fields: ctx, arg
func (_m *Querier) IsEventAdmin(ctx context.Context, arg database.IsEventAdminParams) (pgtype.Bool, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for IsEventAdmin")
	}

	var r0 pgtype.Bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.IsEventAdminParams) (pgtype.Bool, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.IsEventAdminParams) pgtype.Bool); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(pgtype.Bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.IsEventAdminParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsOrgAdmin provides a mock function with given fields: ctx, arg
func (_m *Querier) IsOrgAdmin(ctx context.Context, arg database.IsOrgAdminParams) (pgtype.Bool, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for IsOrgAdmin")
	}

	var r0 pgtype.Bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.IsOrgAdminParams) (pgtype.Bool, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.IsOrgAdminParams) pgtype.Bool); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(pgtype.Bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.IsOrgAdminParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListBotTokens provides a mock function with given fields: ctx
func (_m *Querier) ListBotTokens(ctx context.Context) ([]database.ListBotTokensRow, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListBotTokens")
	}

	var r0 []database.ListBotTokensRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]database.ListBotTokensRow, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []database.ListBotTokensRow); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.ListBotTokensRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListEvents provides a mock function with given fields: ctx, arg
func (_m *Querier) ListEvents(ctx context.Context, arg database.ListEventsParams) ([]database.Event, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListEvents")
	}

	var r0 []database.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.ListEventsParams) ([]database.Event, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.ListEventsParams) []database.Event); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.ListEventsParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListEventsByOrg provides a mock function with given fields: ctx, arg
func (_m *Querier) ListEventsByOrg(ctx context.Context, arg database.ListEventsByOrgParams) ([]database.Event, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListEventsByOrg")
	}

	var r0 []database.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.ListEventsByOrgParams) ([]database.Event, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.ListEventsByOrgParams) []database.Event); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.ListEventsByOrgParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListLinksByOrg provides a mock function with given fields: ctx, oid
func (_m *Querier) ListLinksByOrg(ctx context.Context, oid uuid.UUID) ([]database.Link, error) {
	ret := _m.Called(ctx, oid)

	if len(ret) == 0 {
		panic("no return value specified for ListLinksByOrg")
	}

	var r0 []database.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]database.Link, error)); ok {
		return rf(ctx, oid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []database.Link); ok {
		r0 = rf(ctx, oid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Link)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, oid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListOrganizations provides a mock function with given fields: ctx, arg
func (_m *Querier) ListOrganizations(ctx context.Context, arg database.ListOrganizationsParams) ([]database.Organization, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListOrganizations")
	}

	var r0 []database.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.ListOrganizationsParams) ([]database.Organization, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.ListOrganizationsParams) []database.Organization); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.ListOrganizationsParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUsers provides a mock function with given fields: ctx, arg
func (_m *Querier) ListUsers(ctx context.Context, arg database.ListUsersParams) ([]database.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []database.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.ListUsersParams) ([]database.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.ListUsersParams) []database.User); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.ListUsersParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogLinkVisit provides a mock function with given fields: ctx, arg
func (_m *Querier) LogLinkVisit(ctx context.Context, arg database.LogLinkVisitParams) (database.LinkVisit, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for LogLinkVisit")
	}

	var r0 database.LinkVisit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.LogLinkVisitParams) (database.LinkVisit, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.LogLinkVisitParams) database.LinkVisit); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(database.LinkVisit)
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.LogLinkVisitParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterForEvent provides a mock function with given fields: ctx, arg
func (_m *Querier) RegisterForEvent(ctx context.Context, arg database.RegisterForEventParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for RegisterForEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.RegisterForEventParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveOrgMember provides a mock function with given fields: ctx, arg
func (_m *Querier) RemoveOrgMember(ctx context.Context, arg database.RemoveOrgMemberParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for RemoveOrgMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.RemoveOrgMemberParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokeBotToken provides a mock function with given fields: ctx, tokenID
func (_m *Querier) RevokeBotToken(ctx context.Context, tokenID uuid.UUID) error {
	ret := _m.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeBotToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, tokenID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UnregisterFromEvent provides a mock function with given fields: ctx, arg
func (_m *Querier) UnregisterFromEvent(ctx context.Context, arg database.UnregisterFromEventParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UnregisterFromEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.UnregisterFromEventParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateBotTokenLastUsed provides a mock function with given fields: ctx, tokenID
func (_m *Querier) UpdateBotTokenLastUsed(ctx context.Context, tokenID uuid.UUID) error {
	ret := _m.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBotTokenLastUsed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, tokenID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateEvent provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateEvent(ctx context.Context, arg database.UpdateEventParams) (database.Event, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEvent")
	}

	var r0 database.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.UpdateEventParams) (database.Event, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.UpdateEventParams) database.Event); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(database.Event)
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.UpdateEventParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateLink provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateLink(ctx context.Context, arg database.UpdateLinkParams) (database.Link, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLink")
	}

	var r0 database.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.UpdateLinkParams) (database.Link, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.UpdateLinkParams) database.Link); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(database.Link)
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.UpdateLinkParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOrganization provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateOrganization(ctx context.Context, arg database.UpdateOrganizationParams) (database.Organization, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrganization")
	}

	var r0 database.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.UpdateOrganizationParams) (database.Organization, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.UpdateOrganizationParams) database.Organization); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(database.Organization)
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.UpdateOrganizationParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateUser(ctx context.Context, arg database.UpdateUserParams) (database.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 database.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.UpdateUserParams) (database.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.UpdateUserParams) database.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(database.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.UpdateUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewQuerier creates a new instance of Querier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Querier {
	mock := &Querier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
