package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"time"

	"github.com/capyrpi/api/internal/config"
	"github.com/capyrpi/api/internal/database"
	"github.com/capyrpi/api/internal/middleware"
	"github.com/golang-jwt/jwt/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/joho/godotenv"
)

func main() {
	envFile := flag.String("env", ".env", "Path to .env file")
	flag.Parse()

	if err := godotenv.Load(*envFile); err != nil {
		log.Printf("Warning: Error loading .env file: %v", err)
	}

	cfg, err := config.Load()
	if err != nil {
		log.Fatalf("Failed to load config: %v", err)
	}

	// Connect to DB
	pool, err := pgxpool.New(context.Background(), cfg.Database.URL)
	if err != nil {
		log.Fatalf("Unable to connect to database: %v", err)
	}
	defer pool.Close()

	queries := database.New(pool)
	ctx := context.Background()

	// Create User
	// Note: UID is generated by DB
	user, err := queries.CreateUser(ctx, database.CreateUserParams{
		FirstName:     "Dev",
		LastName:      "User",
		PersonalEmail: pgtype.Text{String: "dev@example.com", Valid: true},
		Role:          database.NullUserRole{UserRole: database.UserRoleStudent, Valid: true},
	})
	if err != nil {
		// Try to find existing if duplicate
		log.Printf("User creation failed (likely exists), finding by email...")
		user, err = queries.GetUserByEmail(ctx, pgtype.Text{String: "dev@example.com", Valid: true})
		if err != nil {
			log.Fatalf("Failed to create or find user: %v", err)
		}
	}

	// Create Token
	claims := middleware.UserClaims{
		UserID: user.Uid.String(),
		Email:  user.PersonalEmail.String,
		Role:   "student",
		RegisteredClaims: jwt.RegisteredClaims{
			ExpiresAt: jwt.NewNumericDate(time.Now().Add(24 * time.Hour)),
			IssuedAt:  jwt.NewNumericDate(time.Now()),
		},
	}

	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	tokenString, err := token.SignedString([]byte(cfg.JWT.Secret))
	if err != nil {
		log.Fatalf("Failed to sign token: %v", err)
	}

	fmt.Println("\n✅ User Seeded & Token Generated!")
	fmt.Println("---------------------------------------------------")
	fmt.Printf("User Name: %s %s\n", user.FirstName, user.LastName)
	fmt.Printf("User ID:   %s\n", user.Uid)
	fmt.Println("---------------------------------------------------")
	fmt.Println("\nTry this command now:")
	fmt.Printf("curl -H \"Authorization: Bearer %s\" http://localhost:8080/api/v1/auth/me\n", tokenString)
}
