// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type UserRole string

const (
	UserRoleStudent  UserRole = "student"
	UserRoleAlumni   UserRole = "alumni"
	UserRoleFaculty  UserRole = "faculty"
	UserRoleExternal UserRole = "external"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type BotToken struct {
	TokenID    uuid.UUID        `json:"token_id"`
	TokenHash  string           `json:"token_hash"`
	Name       string           `json:"name"`
	CreatedBy  uuid.UUID        `json:"created_by"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	LastUsedAt pgtype.Timestamp `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
	IsActive   pgtype.Bool      `json:"is_active"`
}

type Event struct {
	Eid          uuid.UUID        `json:"eid"`
	Location     pgtype.Text      `json:"location"`
	EventTime    pgtype.Timestamp `json:"event_time"`
	Description  pgtype.Text      `json:"description"`
	DateCreated  pgtype.Date      `json:"date_created"`
	DateModified pgtype.Date      `json:"date_modified"`
}

type EventHosting struct {
	Eid uuid.UUID `json:"eid"`
	Oid uuid.UUID `json:"oid"`
}

type EventRegistration struct {
	Uid            uuid.UUID   `json:"uid"`
	Eid            uuid.UUID   `json:"eid"`
	IsAttending    pgtype.Bool `json:"is_attending"`
	IsAdmin        pgtype.Bool `json:"is_admin"`
	DateRegistered pgtype.Date `json:"date_registered"`
}

type OrgMember struct {
	Uid        uuid.UUID   `json:"uid"`
	Oid        uuid.UUID   `json:"oid"`
	IsAdmin    pgtype.Bool `json:"is_admin"`
	DateJoined pgtype.Date `json:"date_joined"`
	LastActive pgtype.Date `json:"last_active"`
}

type Organization struct {
	Oid          uuid.UUID   `json:"oid"`
	Name         string      `json:"name"`
	DateCreated  pgtype.Date `json:"date_created"`
	DateModified pgtype.Date `json:"date_modified"`
}

type User struct {
	Uid           uuid.UUID    `json:"uid"`
	FirstName     string       `json:"first_name"`
	LastName      string       `json:"last_name"`
	PersonalEmail pgtype.Text  `json:"personal_email"`
	SchoolEmail   pgtype.Text  `json:"school_email"`
	Phone         pgtype.Text  `json:"phone"`
	GradYear      pgtype.Int4  `json:"grad_year"`
	Role          NullUserRole `json:"role"`
	DateCreated   pgtype.Date  `json:"date_created"`
	DateModified  pgtype.Date  `json:"date_modified"`
}
