// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddEventHost(ctx context.Context, arg AddEventHostParams) error
	AddOrgMember(ctx context.Context, arg AddOrgMemberParams) error
	CreateBotToken(ctx context.Context, arg CreateBotTokenParams) (BotToken, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	// Link Queries
	CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error)
	CreateOrgDiscord(ctx context.Context, arg CreateOrgDiscordParams) error
	CreateOrganization(ctx context.Context, name string) (Organization, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteEvent(ctx context.Context, eid uuid.UUID) error
	DeleteLink(ctx context.Context, lid uuid.UUID) error
	DeleteOrganization(ctx context.Context, oid uuid.UUID) error
	DeleteUser(ctx context.Context, uid uuid.UUID) error
	// Bot Token Queries
	GetBotTokenByID(ctx context.Context, tokenID uuid.UUID) (BotToken, error)
	GetEventByID(ctx context.Context, eid uuid.UUID) (EventsWithOrgID, error)
	GetEventRegistrations(ctx context.Context, eid uuid.UUID) ([]GetEventRegistrationsRow, error)
	GetLinkByEndpointURL(ctx context.Context, endpointUrl string) (Link, error)
	GetLinkByLID(ctx context.Context, lid uuid.UUID) (Link, error)
	GetOrgMembers(ctx context.Context, oid uuid.UUID) ([]GetOrgMembersRow, error)
	GetOrganizationByGuildID(ctx context.Context, guildID int64) (GetOrganizationByGuildIDRow, error)
	GetOrganizationByID(ctx context.Context, oid uuid.UUID) (Organization, error)
	GetTotalVisits(ctx context.Context, lid uuid.UUID) (int64, error)
	GetUserByEmail(ctx context.Context, personalEmail pgtype.Text) (User, error)
	GetUserByID(ctx context.Context, uid uuid.UUID) (User, error)
	GetUserEvents(ctx context.Context, uid uuid.UUID) ([]GetUserEventsRow, error)
	GetUserOrganizations(ctx context.Context, uid uuid.UUID) ([]GetUserOrganizationsRow, error)
	IsEventAdmin(ctx context.Context, arg IsEventAdminParams) (pgtype.Bool, error)
	IsOrgAdmin(ctx context.Context, arg IsOrgAdminParams) (pgtype.Bool, error)
	ListBotTokens(ctx context.Context) ([]ListBotTokensRow, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]EventsWithOrgID, error)
	ListEventsByOrg(ctx context.Context, arg ListEventsByOrgParams) ([]EventsWithOrgID, error)
	ListLinksByOrg(ctx context.Context, oid uuid.UUID) ([]Link, error)
	ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]ListOrganizationsRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	LogLinkVisit(ctx context.Context, arg LogLinkVisitParams) (LinkVisit, error)
	RegisterForEvent(ctx context.Context, arg RegisterForEventParams) error
	RemoveOrgMember(ctx context.Context, arg RemoveOrgMemberParams) error
	RevokeBotToken(ctx context.Context, tokenID uuid.UUID) error
	UnregisterFromEvent(ctx context.Context, arg UnregisterFromEventParams) error
	UpdateBotTokenLastUsed(ctx context.Context, tokenID uuid.UUID) error
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (UpdateEventRow, error)
	UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
