// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addEventHost = `-- name: AddEventHost :exec
INSERT INTO event_hosting (eid, oid)
VALUES ($1, $2)
ON CONFLICT (eid, oid) DO NOTHING
`

type AddEventHostParams struct {
	Eid uuid.UUID `json:"eid"`
	Oid uuid.UUID `json:"oid"`
}

func (q *Queries) AddEventHost(ctx context.Context, arg AddEventHostParams) error {
	_, err := q.db.Exec(ctx, addEventHost, arg.Eid, arg.Oid)
	return err
}

const addOrgMember = `-- name: AddOrgMember :exec
INSERT INTO org_members (uid, oid, is_admin)
VALUES ($1, $2, $3)
ON CONFLICT (uid, oid) DO UPDATE SET is_admin = $3
`

type AddOrgMemberParams struct {
	Uid     uuid.UUID   `json:"uid"`
	Oid     uuid.UUID   `json:"oid"`
	IsAdmin pgtype.Bool `json:"is_admin"`
}

func (q *Queries) AddOrgMember(ctx context.Context, arg AddOrgMemberParams) error {
	_, err := q.db.Exec(ctx, addOrgMember, arg.Uid, arg.Oid, arg.IsAdmin)
	return err
}

const createBotToken = `-- name: CreateBotToken :one
INSERT INTO bot_tokens (token_hash, name, created_by, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING token_id, token_hash, name, created_by, created_at, last_used_at, expires_at, is_active
`

type CreateBotTokenParams struct {
	TokenHash string           `json:"token_hash"`
	Name      string           `json:"name"`
	CreatedBy uuid.UUID        `json:"created_by"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateBotToken(ctx context.Context, arg CreateBotTokenParams) (BotToken, error) {
	row := q.db.QueryRow(ctx, createBotToken,
		arg.TokenHash,
		arg.Name,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i BotToken
	err := row.Scan(
		&i.TokenID,
		&i.TokenHash,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.IsActive,
	)
	return i, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (title, location, event_time, description)
VALUES ($1, $2, $3, $4)
RETURNING eid, title, location, event_time, description, date_created, date_modified
`

type CreateEventParams struct {
	Title       pgtype.Text      `json:"title"`
	Location    pgtype.Text      `json:"location"`
	EventTime   pgtype.Timestamp `json:"event_time"`
	Description pgtype.Text      `json:"description"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Title,
		arg.Location,
		arg.EventTime,
		arg.Description,
	)
	var i Event
	err := row.Scan(
		&i.Eid,
		&i.Title,
		&i.Location,
		&i.EventTime,
		&i.Description,
		&i.DateCreated,
		&i.DateModified,
	)
	return i, err
}

const createLink = `-- name: CreateLink :one

INSERT INTO links (endpoint_url, dest_url, oid)
VALUES ($1, $2, $3)
RETURNING lid, endpoint_url, dest_url, oid, created_at
`

type CreateLinkParams struct {
	EndpointUrl string    `json:"endpoint_url"`
	DestUrl     string    `json:"dest_url"`
	Oid         uuid.UUID `json:"oid"`
}

// Link Queries
func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink, arg.EndpointUrl, arg.DestUrl, arg.Oid)
	var i Link
	err := row.Scan(
		&i.Lid,
		&i.EndpointUrl,
		&i.DestUrl,
		&i.Oid,
		&i.CreatedAt,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name)
VALUES ($1)
RETURNING oid, name, date_created, date_modified
`

func (q *Queries) CreateOrganization(ctx context.Context, name string) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, name)
	var i Organization
	err := row.Scan(
		&i.Oid,
		&i.Name,
		&i.DateCreated,
		&i.DateModified,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (first_name, last_name, personal_email, school_email, phone, grad_year, role)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING uid, first_name, last_name, personal_email, school_email, phone, grad_year, role, date_created, date_modified
`

type CreateUserParams struct {
	FirstName     string       `json:"first_name"`
	LastName      string       `json:"last_name"`
	PersonalEmail pgtype.Text  `json:"personal_email"`
	SchoolEmail   pgtype.Text  `json:"school_email"`
	Phone         pgtype.Text  `json:"phone"`
	GradYear      pgtype.Int4  `json:"grad_year"`
	Role          NullUserRole `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.PersonalEmail,
		arg.SchoolEmail,
		arg.Phone,
		arg.GradYear,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.Uid,
		&i.FirstName,
		&i.LastName,
		&i.PersonalEmail,
		&i.SchoolEmail,
		&i.Phone,
		&i.GradYear,
		&i.Role,
		&i.DateCreated,
		&i.DateModified,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE eid = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, eid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvent, eid)
	return err
}

const deleteLink = `-- name: DeleteLink :exec
DELETE FROM links WHERE lid = $1
`

func (q *Queries) DeleteLink(ctx context.Context, lid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLink, lid)
	return err
}

const deleteOrganization = `-- name: DeleteOrganization :exec
DELETE FROM organizations WHERE oid = $1
`

func (q *Queries) DeleteOrganization(ctx context.Context, oid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganization, oid)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE uid = $1
`

func (q *Queries) DeleteUser(ctx context.Context, uid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, uid)
	return err
}

const getBotTokenByID = `-- name: GetBotTokenByID :one

SELECT token_id, token_hash, name, created_by, created_at, last_used_at, expires_at, is_active FROM bot_tokens WHERE token_id = $1
`

// Bot Token Queries
func (q *Queries) GetBotTokenByID(ctx context.Context, tokenID uuid.UUID) (BotToken, error) {
	row := q.db.QueryRow(ctx, getBotTokenByID, tokenID)
	var i BotToken
	err := row.Scan(
		&i.TokenID,
		&i.TokenHash,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.IsActive,
	)
	return i, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT eid, title, location, event_time, description, date_created, date_modified FROM events WHERE eid = $1
`

func (q *Queries) GetEventByID(ctx context.Context, eid uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, eid)
	var i Event
	err := row.Scan(
		&i.Eid,
		&i.Title,
		&i.Location,
		&i.EventTime,
		&i.Description,
		&i.DateCreated,
		&i.DateModified,
	)
	return i, err
}

const getEventRegistrations = `-- name: GetEventRegistrations :many
SELECT u.uid, u.first_name, u.last_name, u.personal_email, u.school_email, u.phone, u.grad_year, u.role, u.date_created, u.date_modified, er.is_attending, er.is_admin, er.date_registered
FROM users u
JOIN event_registrations er ON u.uid = er.uid
WHERE er.eid = $1
ORDER BY er.date_registered
`

type GetEventRegistrationsRow struct {
	Uid            uuid.UUID    `json:"uid"`
	FirstName      string       `json:"first_name"`
	LastName       string       `json:"last_name"`
	PersonalEmail  pgtype.Text  `json:"personal_email"`
	SchoolEmail    pgtype.Text  `json:"school_email"`
	Phone          pgtype.Text  `json:"phone"`
	GradYear       pgtype.Int4  `json:"grad_year"`
	Role           NullUserRole `json:"role"`
	DateCreated    pgtype.Date  `json:"date_created"`
	DateModified   pgtype.Date  `json:"date_modified"`
	IsAttending    pgtype.Bool  `json:"is_attending"`
	IsAdmin        pgtype.Bool  `json:"is_admin"`
	DateRegistered pgtype.Date  `json:"date_registered"`
}

func (q *Queries) GetEventRegistrations(ctx context.Context, eid uuid.UUID) ([]GetEventRegistrationsRow, error) {
	rows, err := q.db.Query(ctx, getEventRegistrations, eid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEventRegistrationsRow{}
	for rows.Next() {
		var i GetEventRegistrationsRow
		if err := rows.Scan(
			&i.Uid,
			&i.FirstName,
			&i.LastName,
			&i.PersonalEmail,
			&i.SchoolEmail,
			&i.Phone,
			&i.GradYear,
			&i.Role,
			&i.DateCreated,
			&i.DateModified,
			&i.IsAttending,
			&i.IsAdmin,
			&i.DateRegistered,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinkByEndpointURL = `-- name: GetLinkByEndpointURL :one
SELECT lid, endpoint_url, dest_url, oid, created_at FROM links WHERE endpoint_url = $1
`

func (q *Queries) GetLinkByEndpointURL(ctx context.Context, endpointUrl string) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByEndpointURL, endpointUrl)
	var i Link
	err := row.Scan(
		&i.Lid,
		&i.EndpointUrl,
		&i.DestUrl,
		&i.Oid,
		&i.CreatedAt,
	)
	return i, err
}

const getLinkByLID = `-- name: GetLinkByLID :one
SELECT lid, endpoint_url, dest_url, oid, created_at FROM links WHERE lid = $1
`

func (q *Queries) GetLinkByLID(ctx context.Context, lid uuid.UUID) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByLID, lid)
	var i Link
	err := row.Scan(
		&i.Lid,
		&i.EndpointUrl,
		&i.DestUrl,
		&i.Oid,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgMembers = `-- name: GetOrgMembers :many
SELECT u.uid, u.first_name, u.last_name, u.personal_email, u.school_email, u.phone, u.grad_year, u.role, u.date_created, u.date_modified, om.is_admin, om.date_joined, om.last_active
FROM users u
JOIN org_members om ON u.uid = om.uid
WHERE om.oid = $1
ORDER BY u.last_name, u.first_name
`

type GetOrgMembersRow struct {
	Uid           uuid.UUID    `json:"uid"`
	FirstName     string       `json:"first_name"`
	LastName      string       `json:"last_name"`
	PersonalEmail pgtype.Text  `json:"personal_email"`
	SchoolEmail   pgtype.Text  `json:"school_email"`
	Phone         pgtype.Text  `json:"phone"`
	GradYear      pgtype.Int4  `json:"grad_year"`
	Role          NullUserRole `json:"role"`
	DateCreated   pgtype.Date  `json:"date_created"`
	DateModified  pgtype.Date  `json:"date_modified"`
	IsAdmin       pgtype.Bool  `json:"is_admin"`
	DateJoined    pgtype.Date  `json:"date_joined"`
	LastActive    pgtype.Date  `json:"last_active"`
}

func (q *Queries) GetOrgMembers(ctx context.Context, oid uuid.UUID) ([]GetOrgMembersRow, error) {
	rows, err := q.db.Query(ctx, getOrgMembers, oid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOrgMembersRow{}
	for rows.Next() {
		var i GetOrgMembersRow
		if err := rows.Scan(
			&i.Uid,
			&i.FirstName,
			&i.LastName,
			&i.PersonalEmail,
			&i.SchoolEmail,
			&i.Phone,
			&i.GradYear,
			&i.Role,
			&i.DateCreated,
			&i.DateModified,
			&i.IsAdmin,
			&i.DateJoined,
			&i.LastActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT oid, name, date_created, date_modified FROM organizations WHERE oid = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, oid uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, oid)
	var i Organization
	err := row.Scan(
		&i.Oid,
		&i.Name,
		&i.DateCreated,
		&i.DateModified,
	)
	return i, err
}

const getTotalVisits = `-- name: GetTotalVisits :one
SELECT COUNT(*) FROM link_visits WHERE lid = $1
`

func (q *Queries) GetTotalVisits(ctx context.Context, lid uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalVisits, lid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT uid, first_name, last_name, personal_email, school_email, phone, grad_year, role, date_created, date_modified FROM users WHERE personal_email = $1 OR school_email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, personalEmail pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, personalEmail)
	var i User
	err := row.Scan(
		&i.Uid,
		&i.FirstName,
		&i.LastName,
		&i.PersonalEmail,
		&i.SchoolEmail,
		&i.Phone,
		&i.GradYear,
		&i.Role,
		&i.DateCreated,
		&i.DateModified,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT uid, first_name, last_name, personal_email, school_email, phone, grad_year, role, date_created, date_modified FROM users WHERE uid = $1
`

func (q *Queries) GetUserByID(ctx context.Context, uid uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, uid)
	var i User
	err := row.Scan(
		&i.Uid,
		&i.FirstName,
		&i.LastName,
		&i.PersonalEmail,
		&i.SchoolEmail,
		&i.Phone,
		&i.GradYear,
		&i.Role,
		&i.DateCreated,
		&i.DateModified,
	)
	return i, err
}

const getUserEvents = `-- name: GetUserEvents :many
SELECT e.eid, e.title, e.location, e.event_time, e.description, e.date_created, e.date_modified, er.is_attending, er.is_admin, er.date_registered
FROM events e
JOIN event_registrations er ON e.eid = er.eid
WHERE er.uid = $1
ORDER BY e.event_time DESC
`

type GetUserEventsRow struct {
	Eid            uuid.UUID        `json:"eid"`
	Title          pgtype.Text      `json:"title"`
	Location       pgtype.Text      `json:"location"`
	EventTime      pgtype.Timestamp `json:"event_time"`
	Description    pgtype.Text      `json:"description"`
	DateCreated    pgtype.Date      `json:"date_created"`
	DateModified   pgtype.Date      `json:"date_modified"`
	IsAttending    pgtype.Bool      `json:"is_attending"`
	IsAdmin        pgtype.Bool      `json:"is_admin"`
	DateRegistered pgtype.Date      `json:"date_registered"`
}

func (q *Queries) GetUserEvents(ctx context.Context, uid uuid.UUID) ([]GetUserEventsRow, error) {
	rows, err := q.db.Query(ctx, getUserEvents, uid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserEventsRow{}
	for rows.Next() {
		var i GetUserEventsRow
		if err := rows.Scan(
			&i.Eid,
			&i.Title,
			&i.Location,
			&i.EventTime,
			&i.Description,
			&i.DateCreated,
			&i.DateModified,
			&i.IsAttending,
			&i.IsAdmin,
			&i.DateRegistered,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserOrganizations = `-- name: GetUserOrganizations :many
SELECT o.oid, o.name, o.date_created, o.date_modified, om.is_admin, om.date_joined
FROM organizations o
JOIN org_members om ON o.oid = om.oid
WHERE om.uid = $1
ORDER BY o.name
`

type GetUserOrganizationsRow struct {
	Oid          uuid.UUID   `json:"oid"`
	Name         string      `json:"name"`
	DateCreated  pgtype.Date `json:"date_created"`
	DateModified pgtype.Date `json:"date_modified"`
	IsAdmin      pgtype.Bool `json:"is_admin"`
	DateJoined   pgtype.Date `json:"date_joined"`
}

func (q *Queries) GetUserOrganizations(ctx context.Context, uid uuid.UUID) ([]GetUserOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, getUserOrganizations, uid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserOrganizationsRow{}
	for rows.Next() {
		var i GetUserOrganizationsRow
		if err := rows.Scan(
			&i.Oid,
			&i.Name,
			&i.DateCreated,
			&i.DateModified,
			&i.IsAdmin,
			&i.DateJoined,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isEventAdmin = `-- name: IsEventAdmin :one
SELECT EXISTS (
    SELECT 1
    FROM event_registrations er
    WHERE er.uid = $1
      AND er.eid = $2
      AND er.is_admin = TRUE
)
OR EXISTS (
    SELECT 1
    FROM event_hosting eh
    JOIN org_members om ON om.oid = eh.oid
    WHERE eh.eid = $2
      AND om.uid = $1
      AND om.is_admin = TRUE
)
`

type IsEventAdminParams struct {
	Uid uuid.UUID `json:"uid"`
	Eid uuid.UUID `json:"eid"`
}

func (q *Queries) IsEventAdmin(ctx context.Context, arg IsEventAdminParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, isEventAdmin, arg.Uid, arg.Eid)
	var column_1 pgtype.Bool
	err := row.Scan(&column_1)
	return column_1, err
}

const isOrgAdmin = `-- name: IsOrgAdmin :one
SELECT is_admin FROM org_members WHERE uid = $1 AND oid = $2
`

type IsOrgAdminParams struct {
	Uid uuid.UUID `json:"uid"`
	Oid uuid.UUID `json:"oid"`
}

func (q *Queries) IsOrgAdmin(ctx context.Context, arg IsOrgAdminParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, isOrgAdmin, arg.Uid, arg.Oid)
	var is_admin pgtype.Bool
	err := row.Scan(&is_admin)
	return is_admin, err
}

const listBotTokens = `-- name: ListBotTokens :many
SELECT token_id, name, created_by, created_at, last_used_at, expires_at, is_active
FROM bot_tokens
ORDER BY created_at DESC
`

type ListBotTokensRow struct {
	TokenID    uuid.UUID        `json:"token_id"`
	Name       string           `json:"name"`
	CreatedBy  uuid.UUID        `json:"created_by"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	LastUsedAt pgtype.Timestamp `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
	IsActive   pgtype.Bool      `json:"is_active"`
}

func (q *Queries) ListBotTokens(ctx context.Context) ([]ListBotTokensRow, error) {
	rows, err := q.db.Query(ctx, listBotTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBotTokensRow{}
	for rows.Next() {
		var i ListBotTokensRow
		if err := rows.Scan(
			&i.TokenID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT eid, title, location, event_time, description, date_created, date_modified FROM events ORDER BY event_time DESC LIMIT $1 OFFSET $2
`

type ListEventsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.Eid,
			&i.Title,
			&i.Location,
			&i.EventTime,
			&i.Description,
			&i.DateCreated,
			&i.DateModified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByOrg = `-- name: ListEventsByOrg :many
SELECT e.eid, e.title, e.location, e.event_time, e.description, e.date_created, e.date_modified
FROM events e
JOIN event_hosting eh ON e.eid = eh.eid
WHERE eh.oid = $1
ORDER BY e.event_time DESC
LIMIT $2 OFFSET $3
`

type ListEventsByOrgParams struct {
	Oid    uuid.UUID `json:"oid"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListEventsByOrg(ctx context.Context, arg ListEventsByOrgParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByOrg, arg.Oid, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.Eid,
			&i.Title,
			&i.Location,
			&i.EventTime,
			&i.Description,
			&i.DateCreated,
			&i.DateModified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinksByOrg = `-- name: ListLinksByOrg :many
SELECT lid, endpoint_url, dest_url, oid, created_at FROM links WHERE oid = $1 ORDER BY created_at DESC
`

func (q *Queries) ListLinksByOrg(ctx context.Context, oid uuid.UUID) ([]Link, error) {
	rows, err := q.db.Query(ctx, listLinksByOrg, oid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Link{}
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.Lid,
			&i.EndpointUrl,
			&i.DestUrl,
			&i.Oid,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT oid, name, date_created, date_modified FROM organizations ORDER BY name LIMIT $1 OFFSET $2
`

type ListOrganizationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.Oid,
			&i.Name,
			&i.DateCreated,
			&i.DateModified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT uid, first_name, last_name, personal_email, school_email, phone, grad_year, role, date_created, date_modified FROM users ORDER BY last_name, first_name LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Uid,
			&i.FirstName,
			&i.LastName,
			&i.PersonalEmail,
			&i.SchoolEmail,
			&i.Phone,
			&i.GradYear,
			&i.Role,
			&i.DateCreated,
			&i.DateModified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logLinkVisit = `-- name: LogLinkVisit :one
INSERT INTO link_visits (lid, uid)
VALUES ($1, $2)
RETURNING lvid, lid, uid, created_at
`

type LogLinkVisitParams struct {
	Lid uuid.UUID   `json:"lid"`
	Uid pgtype.UUID `json:"uid"`
}

func (q *Queries) LogLinkVisit(ctx context.Context, arg LogLinkVisitParams) (LinkVisit, error) {
	row := q.db.QueryRow(ctx, logLinkVisit, arg.Lid, arg.Uid)
	var i LinkVisit
	err := row.Scan(
		&i.Lvid,
		&i.Lid,
		&i.Uid,
		&i.CreatedAt,
	)
	return i, err
}

const registerForEvent = `-- name: RegisterForEvent :exec
INSERT INTO event_registrations (uid, eid, is_attending)
VALUES ($1, $2, $3)
ON CONFLICT (uid, eid) DO UPDATE SET is_attending = $3
`

type RegisterForEventParams struct {
	Uid         uuid.UUID   `json:"uid"`
	Eid         uuid.UUID   `json:"eid"`
	IsAttending pgtype.Bool `json:"is_attending"`
}

func (q *Queries) RegisterForEvent(ctx context.Context, arg RegisterForEventParams) error {
	_, err := q.db.Exec(ctx, registerForEvent, arg.Uid, arg.Eid, arg.IsAttending)
	return err
}

const removeOrgMember = `-- name: RemoveOrgMember :exec
DELETE FROM org_members WHERE uid = $1 AND oid = $2
`

type RemoveOrgMemberParams struct {
	Uid uuid.UUID `json:"uid"`
	Oid uuid.UUID `json:"oid"`
}

func (q *Queries) RemoveOrgMember(ctx context.Context, arg RemoveOrgMemberParams) error {
	_, err := q.db.Exec(ctx, removeOrgMember, arg.Uid, arg.Oid)
	return err
}

const revokeBotToken = `-- name: RevokeBotToken :exec
UPDATE bot_tokens SET is_active = false WHERE token_id = $1
`

func (q *Queries) RevokeBotToken(ctx context.Context, tokenID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeBotToken, tokenID)
	return err
}

const unregisterFromEvent = `-- name: UnregisterFromEvent :exec
DELETE FROM event_registrations WHERE uid = $1 AND eid = $2
`

type UnregisterFromEventParams struct {
	Uid uuid.UUID `json:"uid"`
	Eid uuid.UUID `json:"eid"`
}

func (q *Queries) UnregisterFromEvent(ctx context.Context, arg UnregisterFromEventParams) error {
	_, err := q.db.Exec(ctx, unregisterFromEvent, arg.Uid, arg.Eid)
	return err
}

const updateBotTokenLastUsed = `-- name: UpdateBotTokenLastUsed :exec
UPDATE bot_tokens SET last_used_at = CURRENT_TIMESTAMP WHERE token_id = $1
`

func (q *Queries) UpdateBotTokenLastUsed(ctx context.Context, tokenID uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateBotTokenLastUsed, tokenID)
	return err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET title = COALESCE($2, title),
    location = COALESCE($3, location),
    event_time = COALESCE($4, event_time),
    description = COALESCE($5, description)
WHERE eid = $1
RETURNING eid, title, location, event_time, description, date_created, date_modified
`

type UpdateEventParams struct {
	Eid         uuid.UUID        `json:"eid"`
	Title       pgtype.Text      `json:"title"`
	Location    pgtype.Text      `json:"location"`
	EventTime   pgtype.Timestamp `json:"event_time"`
	Description pgtype.Text      `json:"description"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.Eid,
		arg.Title,
		arg.Location,
		arg.EventTime,
		arg.Description,
	)
	var i Event
	err := row.Scan(
		&i.Eid,
		&i.Title,
		&i.Location,
		&i.EventTime,
		&i.Description,
		&i.DateCreated,
		&i.DateModified,
	)
	return i, err
}

const updateLink = `-- name: UpdateLink :one
UPDATE links
SET endpoint_url = COALESCE($2, endpoint_url),
    dest_url = COALESCE($3, dest_url)
WHERE lid = $1
RETURNING lid, endpoint_url, dest_url, oid, created_at
`

type UpdateLinkParams struct {
	Lid         uuid.UUID   `json:"lid"`
	EndpointUrl pgtype.Text `json:"endpoint_url"`
	DestUrl     pgtype.Text `json:"dest_url"`
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, updateLink, arg.Lid, arg.EndpointUrl, arg.DestUrl)
	var i Link
	err := row.Scan(
		&i.Lid,
		&i.EndpointUrl,
		&i.DestUrl,
		&i.Oid,
		&i.CreatedAt,
	)
	return i, err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET name = COALESCE($2, name)
WHERE oid = $1
RETURNING oid, name, date_created, date_modified
`

type UpdateOrganizationParams struct {
	Oid  uuid.UUID   `json:"oid"`
	Name pgtype.Text `json:"name"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization, arg.Oid, arg.Name)
	var i Organization
	err := row.Scan(
		&i.Oid,
		&i.Name,
		&i.DateCreated,
		&i.DateModified,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET first_name = COALESCE($2, first_name),
    last_name = COALESCE($3, last_name),
    personal_email = COALESCE($4, personal_email),
    school_email = COALESCE($5, school_email),
    phone = COALESCE($6, phone),
    grad_year = COALESCE($7, grad_year),
    role = COALESCE($8, role)
WHERE uid = $1
RETURNING uid, first_name, last_name, personal_email, school_email, phone, grad_year, role, date_created, date_modified
`

type UpdateUserParams struct {
	Uid           uuid.UUID    `json:"uid"`
	FirstName     pgtype.Text  `json:"first_name"`
	LastName      pgtype.Text  `json:"last_name"`
	PersonalEmail pgtype.Text  `json:"personal_email"`
	SchoolEmail   pgtype.Text  `json:"school_email"`
	Phone         pgtype.Text  `json:"phone"`
	GradYear      pgtype.Int4  `json:"grad_year"`
	Role          NullUserRole `json:"role"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Uid,
		arg.FirstName,
		arg.LastName,
		arg.PersonalEmail,
		arg.SchoolEmail,
		arg.Phone,
		arg.GradYear,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.Uid,
		&i.FirstName,
		&i.LastName,
		&i.PersonalEmail,
		&i.SchoolEmail,
		&i.Phone,
		&i.GradYear,
		&i.Role,
		&i.DateCreated,
		&i.DateModified,
	)
	return i, err
}
